version: 2.0

jobs:
  install_and_build:
    machine: true
    working_directory: ~/challenge
    environment:
    - PY_PATH: /opt/circleci/.pyenv/versions/3.6.3/bin/

    steps:
      - checkout
      - run:
          name: Preparing env
          command: |
              pyenv install 3.6.3
              pyenv global 3.6.3

      - run:
          name: Running bootstrap
          command: |
              bash -x ./bootstrap.sh

      - run:
          name: Install flake8
          command: |
            pip3.6 install -U flake8

      - run:
          name: Run flake 8
          command: |
            export PATH=$PATH:$PY_PATH
            flake8 --exclude=./env/ .
            python3 slk.py --help

workflows:
  version: 2
  build-only:
    jobs:
      - install_and_build
